name: 'Deploy CS 480 Project'
description: 'A GitHub Action that will deploy your CS 480 project to the class server.'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Show files in the action
      run: find ${{ github.action_path }}
      shell: bash
    - name: Show files in the original source code
      run: find ${{ github.workspace }}
      shell: bash
    - name: Run the Python script
      run: python src/deploy.py
      shell: bash