name: 'Deploy CS 480 Project'
description: 'A GitHub Action that will deploy your CS 480 project to the class server.'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run the deployment script
      run: python src/deploy.py
      working-directory: ${{ github.action_path }}
      shell: bash